### ISSUE TITLE
Site won't load with error Invalid column name PasswordExpiresDays and PasswordExpiryWarningDays

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe#1051]
Probably arises from #1012 

After upgrading all packages to latest 8.0.* with MSSQL, the project builds fine, but on running:

An unhandled exception occurred while processing the request.
SqlException: Invalid column name 'PasswordExpiresDays'.
Invalid column name 'PasswordExpiryWarningDays'.
Microsoft.Data.SqlClient.SqlCommand+<>c.<ExecuteDbDataReaderAsync>b__209_0(Task<SqlDataReader> result)

Raw exception:
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'PasswordExpiresDays'.
Invalid column name 'PasswordExpiryWarningDays'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__209_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at cloudscribe.Core.Storage.EFCore.Common.SiteQueries.FetchByFolderName(String folderName, CancellationToken cancellationToken)
   at cloudscribe.Core.Web.Components.SiteContextResolver.ResolveSite(String hostName, String path, CancellationToken cancellationToken)
   at cloudscribe.Core.Web.Components.CachingSiteContextResolver.ResolveSite(String hostName, String path, CancellationToken cancellationToken)
   at cloudscribe.Core.Web.Components.SiteResolver.ResolveAsync(HttpContext context)
   at cloudscribe.Multitenancy.Internal.TenantResolutionMiddleware`1.Invoke(HttpContext context, ITenantResolver`1 tenantResolver)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
ClientConnectionId:682cbe05-c6cc-47b9-90d6-737f1b205f67
Error Number:207,State:1,Class:16

I seem to have all the packages mentioned on #1012 
![image](https://github.com/user-attachments/assets/f2ac8834-b04c-4aa9-9333-af5abe42b5dd)

But it seems the migrations have not run.
The last migration in the target database is 
20240918131738_ShowArchivedAndBlogCategories-20240918

And later... after doing nothing in particular other than trying to run the site again a few times, this resolved itself. I now have no error, and this migration is present:
20240925082208_AddPasswordExpiryFields

So probably no real issue here and this can be closed, but alerting @JimKerslake for info.

**Comment by JimKerslake** [comment]
@CrispinF   the inconsistency of that is curious - Clearly there was an initial failure to run that migration, but that can sometimes be caused by an exception in a previous migration to this one, crashing out all subsequent ones. I would suggest taking a look in the application log, filter to Error level, and look for any error mentioning migration failure... figure out which one failed.  

If there is none such error, then perhaps your local copy of VS didn't initially succeed in getting you a complete fresh set of the most appropriate latest 8.0.* Nugets... your local NuGet cache can sometimes be a bit erratic and sticky on the older ones...
