### ISSUE TITLE
Error while visiting new tenant

### ISSUE THREAD

**Issue by shubhamranjan** [cloudscribe/cloudscribe#723]
Hi,

I am getting the following error while visting a new tenant.

```
System.ArgumentNullException: Value cannot be null. (Parameter 'paths')
   at System.IO.Path.Combine(String[] paths)
   at cloudscribe.Core.Web.TagHelpers.ThemeTagHelperBase.EnsureFileVersionProvider()
   at cloudscribe.Core.Web.TagHelpers.ThemeTagHelperBase.ResolveResourceUrl(String inputUrl)
   at cloudscribe.Core.Web.TagHelpers.ThemeCssLinkTagHelper.Process(TagHelperContext context, TagHelperOutput output)
   at Microsoft.AspNetCore.Razor.TagHelpers.TagHelper.ProcessAsync(TagHelperContext context, TagHelperOutput output)
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.RunAsync(TagHelperExecutionContext executionContext)
```

Steps to reproduce:

1. Setup cloudscribe project with no simple content, backend as postgresql. Update all nuget packages to latest.
2. Configure launchsettings to listen on any ip instead of localhost.
        `"https://*:44320;http://*:14647"`
3. Start app, create new tenant (default theme) with host mapping as `site2.example.com`. Map example.com to 127.0.0.1 in hosts file. 
4. Visit site2.example.com:14647 and you should be seeing the above error if I am doing everything correctly.

Another thing I noticed that whenever we visit the site settings page, the theme dropdown gets set to the first option by default instead of the previous applied value.

**Comment by shubhamranjan** [comment]
I delete the sitefiles folder and it started working. Very weird. Not sure if that actually was the cause or some browser cache issue. If anything pops up again, will update here.
