### ISSUE TITLE
Failure to generate QR code when setting up 2FA

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe#879]
In a tenant in NoDB site configured with social authentication, go to here to set up 2FA
https://mysite.com/tenantfolder/manage/twofactorauthentication
Then click "configure authenticator app" to go to
https://mysite.com/tenantfolder/manage/enableauthenticator

No QR code appears:
![image](https://user-images.githubusercontent.com/10574730/221232597-96734585-72f3-4799-bfe7-cd6b05090074.png)

This html rendered on the page:
```html
<div id="qrCode"><canvas width="150" height="150"></canvas><img style="display: none;"></div>
<div id="qrCodeData" data-url="otpauth://totp/cloudscribe%20Identity%20Client%20Application%202:useremail@whatever.com?secret=FHRTCZQL5YDJXZCJ54G7PX5IZVXHXXXX&amp;issuer=cloudscribe%20Identity%20Client%20Application%202&amp;digits=6"></div>
```

This in browser console:
qrcode.min.js:1 Uncaught Error: code length overflow. (1612>1056)
    at b.createData (qrcode.min.js:1:5199)
    at b.makeImpl (qrcode.min.js:1:2602)
    at b.getBestMaskPattern (qrcode.min.js:1:3024)
    at b.make (qrcode.min.js:1:2028)
    at QRCode.makeCode (qrcode.min.js:1:19621)
    at new QRCode (qrcode.min.js:1:19431)
    at enableauthenticator:176:9

**Comment by JimKerslake** [comment]
Works for me in new template instance out of the box.
May be something to do with length of the URL string above... it has the site name in it twice.

**Comment by JimKerslake** [comment]
It needs to construct and encode a URL of the form:
otpauth://totp/Sample%20Site:jim.kerslake@mysite.com?secret=QNSIJSOE5GUTFLJRDUVKYTTVS3KGP5WZ&issuer=Sample%20Site&digits=6

But I guess if your site name gets too long... it's in there twice.... too much data and it bombs out.
We could add code to truncate the site name to the maximum allowed... at the expense of some generality... could we end up with two sites which both tried to map to the same authenticator app registration..??

**Comment by JimKerslake** [comment]
No I'm wrong about the above - cannot overwhelm it with long site name.
Nor the act of doing this in a second tenant.
Failing to replicate this so far.

**Comment by CrispinF** [comment]
I've upgraded the site with latest fixes, and this still fails 
https://cloudscribe-id-demo-client.esdm.co.uk/app2/manage/enableauthenticator
![image](https://user-images.githubusercontent.com/10574730/223268278-32740454-9716-41ae-8e76-bb81ef5f39f2.png)
![image](https://user-images.githubusercontent.com/10574730/223268523-aba10bb6-fa42-4e6b-87fb-976605a04538.png)
![image](https://user-images.githubusercontent.com/10574730/223268992-47f64e00-1f1b-4e2d-971e-6f0099cb298e.png)

**Comment by JimKerslake** [comment]
Yet this isn't broken in the 'server' version of the site, that you built at the same time....

**Comment by JimKerslake** [comment]
@CrispinF  
OK more direct pragmatic testing:
my first and most likely explanation was correct... any Site Name of > 45 characters causes this breakage
(assuming that spaces count for 3 characters)

(Not sure why my earlier attempts to inject a longer string directly into the method call did not replicate that...)

It seems less than optimal just to summarily truncate the site name for this purpose, but can discuss other options.

**Comment by JimKerslake** [comment]
Anyway, truncating the site name as per the original plan should get us beyond the issues above.  Doing that for now.
cloudscribe.Core.Web up to 6.0.25
